repos:
- repo: https://github.com/datacoves/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: dbt-deps
  - id: dbt-docs-generate
  - id: check-script-has-no-table-name
  - id: check-model-has-all-columns
