name: Multiple CI Run
on:
  workflow_dispatch:
#   pull_request:
#     branches:
#       - main
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - ready_for_review

jobs:
  multiple_ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: 43786
      PULL_REQUEST_ID: ${{ github.event.number }}
      GIT_SHA: ${{ github.event.pull_request.head.sha }}
      GITHUB_TOKEN: ${{ github.token }}
      PR_COMMENT_URL: ${{ github.event.pull_request._links.comments.href }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Run Python Script
        run: |
          pip install dbtc==0.3.3
          python scripts/multiple_ci.py
