# This action will trigger an already created job on dbt Cloud
# The important settings for the job include:
# - defer - defer this job to itself (will always refer to the most recently modified version of production)
# - commands - ensure you're using the state:modified+ selector to only run what's been modified
#              since the last successful run for the job you're deferring to

name: Run Job on Merge
on:
  push:
    branches:
      - main
  
jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: 43786
      JOB_ID: 128558

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Run Merge Job
        run: |
          pip install dbtc==0.3.3
          run=$(dbtc trigger-job \
              --job-id=$JOB_ID \
              --payload='{"cause": "Merging code to main"}')
          echo "RUN_ID=$(echo $run | jq '.data.id')" >> $GITHUB_ENV
      
      - name: Get manifest
        id: manifest
        run: |
          manifest=$(dbtc get-run-artifact \
            --account-id=$DBT_CLOUD_ACCOUNT_ID \
            --run-id=$RUN_ID \
            --path=manifest.json)
          echo $manifest > prod/manifest.json

      - name: Add Manifest to Repo
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.json'
          committer_name: Github Actions
          committer_email: actions@github.com
          message: 'Adding manifest from merge run'
